# docker-compose.yaml
#version: "3.9"
services:
  web:
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myapp/:/var/app
    ports:
      - "8000:8000"
