#ifndef COMPUTERPLAYER_H
#define COMPUTERPLAYER_H

#include <QMainWindow>

class ComputerPlayer {
public:
    ComputerPlayer(){};
    ComputerPlayer(const QStringList &dictionary);

    void setWordPattern(const QString &pattern);

    QChar guessNextLetter();

private:

    QString wordPattern;                // Текущий шаблон слова (например, "_ A _ _ A")
    QVector<QChar> guessedLetters;      // Угаданные буквы


    QStringList filterWordsByPattern(const QString &pattern);

    QHash<QChar, int> countLetterFrequencies(const QStringList &possibleWords);

    int countGuessedVowels(const QString &pattern);

    QChar findMostFrequentLetter(const QHash<QChar, int> &frequencies);

    QChar findMostFrequentConsonant(const QHash<QChar, int> &frequencies);
    QStringList wordDictionary = {
        "человек ",
        "время ",
        "год ",
        "дело ",
        "день ",
        "жизнь ",
        "рука ",
        "работа ",
        "слово ",
        "место ",
        "лицо ",
        "друг ",
        "глаз ",
        "вопрос ",
        "дом ",
        "страна ",
        "мир ",
        "случай ",
        "голова ",
        "ребёнок ",
        "сила ",
        "конец ",
        "вид ",
        "система ",
        "часть ",
        "город ",
        "отношение ",
        "женщина ",
        "деньги ",
        "земля ",
        "машина ",
        "вода ",
        "отец ",
        "проблема ",
        "право ",
        "нога ",
        "решение ",
        "дверь ",
        "образ ",
        "история ",
        "власть ",
        "закон ",
        "война ",
        "бог ",
        "голос ",
        "тысяча ",
        "книга ",
        "ночь ",
        "стол ",
        "имя ",
        "область ",
        "статья ",
        "число ",
        "компания ",
        "народ ",
        "жена ",
        "группа ",
        "развитие ",
        "процесс ",
        "условие ",
        "средство ",
        "начало ",
        "свет ",
        "путь ",
        "уровень ",
        "форма ",
        "связь ",
        "минута ",
        "улица ",
        "вечер ",
        "качество ",
        "мысль ",
        "дорога ",
        "мать ",
        "действие ",
        "месяц ",
        "государство ",
        "язык ",
        "любовь ",
        "взгляд ",
        "мама ",
        "век ",
        "школа ",
        "цель ",
        "общество ",
        "деятельность ",
        "организация ",
        "президент ",
        "комната ",
        "порядок ",
        "момент ",
        "театр ",
        "письмо ",
        "утро ",
        "помощь ",
        "рынок ",
        "значение ",
        "задача ",
        "предприятие ",
        "разговор ",
        "правительство ",
        "производство ",
        "информация ",
        "положение ",
        "time",
        "year",
        "people",
        "way",
        "day",
        "man",
        "thing",
        "woman",
        "life",
        "child",
        "world",
        "school",
        "state",
        "family",
        "student",
        "group",
        "country",
        "problem",
        "hand",
        "part",
        "place",
        "case",
        "week",
        "company",
        "system",
        "program",
        "question",
        "work",
        "government",
        "number",
        "night",
        "point",
        "home",
        "water",
        "room",
        "mother",
        "area",
        "money",
        "story",
        "fact",
        "month",
        "lot",
        "right",
        "study",
        "book",
        "eye",
        "job",
        "word",
        "business",
        "issue",
        "side",
        "kind",
        "head",
        "house",
        "service",
        "friend",
        "father",
        "power",
        "hour",
        "game",
        "line",
        "end",
        "member",
        "law",
        "car",
        "city",
        "community",
        "name",
        "president",
        "team",
        "minute",
        "idea",
        "kid",
        "body",
        "information",
        "back",
        "parent",
        "face",
        "others",
        "level",
        "office",
        "door",
        "health",
        "person",
        "art",
        "war",
        "history",
        "party",
        "result",
        "change",
        "morning",
        "reason",
        "research",
        "girl",
        "guy",
        "moment",
        "air",
        "teacher",
        "force",
        "education",
        "foot",
        "boy",
        "age",
        "policy",
        "process",
        "music",
        "market",
        "sense",
        "nation",
        "plan",
        "college",
        "interest",
        "death",
        "experience",
        "effect",
        "use"
    };
};
#endif // COMPUTERPLAYER_H
